### ISSUE TITLE
Running flower on server

### ISSUE THREAD

**Issue by KrauseBerg** [secgroup/flower#2]
The script ./run_ws.sh does not respond to browser requests when running flower on the server.

**Comment by nicomazz** [comment]
Maybe the reason is that when you run the services on your server, your browser is trying to send the requests to your localhost instead of your server.
Try to check you set the ENV variables correctly (like described here: https://github.com/secgroup/flower#setup ). If the problem persists, try to manually change the ip with your server's one here: https://github.com/secgroup/flower/blob/5aa762d5283370b6a6e3c29e32ab10d1270a68ac/src/data/fetcher.js#L26
Let me know if this fixes the problem!

**Comment by KrauseBerg** [comment]
Yeah, it works!
